name: TrackMoney Pipeline

on:
  workflow_run:
    workflows: [ "SonarCloud CI" ]
    types:
      - completed
    branches:
      - main
      - ci-deploy
  workflow_dispatch:

env:
  APP_NAME: trackmoney

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: ‚¨áÔ∏è Checkout code
        uses: actions/checkout@v4

      - name: üõ†Ô∏è Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: üíæ Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: üß™ Run tests
        run: ./mvnw clean test
  build-and-push:
    runs-on: ubuntu-latest
    name: Build & Push
    needs: tests

    steps:
      - name: ‚¨áÔ∏è Checkout code
        uses: actions/checkout@v4

      - name: üõ†Ô∏è Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: üíæ Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: üè∑Ô∏è Extract version from pom.xml
        id: version
        run: |
          VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "üì¶ Version: $VERSION"

      - name: üì¶ Build application JAR
        run: ./mvnw clean package -DskipTests

      - name: ‚öôÔ∏è Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üîë Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: üèóÔ∏è Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ steps.version.outputs.VERSION }}
          labels: |
            org.opencontainers.image.version=${{ steps.version.outputs.VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.version.outputs.VERSION }}

  deploy:
    runs-on: self-hosted
    name: Deploy
    needs: build-and-push

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      IMAGE_TAG: latest
      APP_PORT: 8080
      SERVER_CONTEXT_PATH: /api/v1
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: 5432
      REDIS_PORT: 6379
      SPRING_MAIL_HOST: ${{ secrets.SPRING_MAIL_HOST }}
      SPRING_MAIL_PORT: ${{ secrets.SPRING_MAIL_PORT }}
      SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
      SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
      API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
      FRONT_URL: ${{ secrets.FRONT_URL }}

    steps:
      - name: ‚¨áÔ∏è Checkout do C√≥digo
        uses: actions/checkout@v4

      - name:  Deploy com Docker Compose local
        run: |
          APP_DIR="/opt/${{ env.APP_NAME }}"
          mkdir -p $APP_DIR
          cp docker-compose.prod.yaml $APP_DIR/docker-compose.prod.yaml

          cd $APP_DIR
          
          docker compose -f docker-compose.prod.yaml down

          docker compose -f docker-compose.prod.yaml up -d --force-recreate --pull

          docker image prune -f
